### ISSUE TITLE
Concurrency?

### ISSUE THREAD

**Issue by barryrobison** [Semantive/blog-step-functions-async-actions#1]
Maybe more of a question than an issue, but with the following code

`    activity_task_response = states_client.get_activity_task(
        activityArn=ASYNC_ACTION_ACTIVITY_ARN,
        workerName=context.function_name,
    )
`

how do you handle Step Function concurrency? ie if there are multiple executions of the Step Function kicked off at the same time,  get_activity_task may not return the task for the "local" wait condition.

Kind regards,
-baz

**Comment by marcin-sucharski** [comment]
Any Execution is allowed to start the nested State Machine for any other concurrent Execution. Lambda handler implemented in `async_invoke.py` cannot assume that the Task Token it will get is tied to its own Execution (and it doesn't assume that - `event` argument to the handler is completely ignored). You can think here about this Lambda as of short-living worker which only purpose is to get the Task Token and pass it somewhere (in our case - to the nested State Machine).

The fact that Lambda invocation is completely unrelated to its Execution forces us to make Execution's success/failure depend solely on the result of the Activity Task and not the Lambda invocation. Thus we are retrying the Lambda and eventually ignoring the errors (because we don't want to fail unrelated Execution).

Downside of such approach is possibility to "lose" Activity Task in case of Lambda failure (keep in mind that business logic shouldn't be put in `async_invoke.py` Lambda - it should only get the Task Token and pass it somewhere). This wouldn't break anything, however, it will increase latency (because Activity Task will be handled by following Executions, and then these Executions will be waiting for following ones and so on). There are several solutions to this problem. We have chosen to periodically call `async_invoke.py` Lambda using CloudWatch Rules. (we can use the same Lambda function because we are ignoring event). So even in the case of lost Activity Task and latency increase caused by that we will "catch up" when additional invocation of the 'async_invoke.py` Lambda is executed by CloudWatch Rules.

In practice I have seen this happen only once after tens/hundreds of thousands  of Executions (and its results is slightly increase in latency until additional invocation of the Lambda is done).

Hope this answers your question. :-)
-Marcin

**Comment by barryrobison** [comment]
Thanks, this does answer my question. I suppose this approach won't work for my Step Functions as I need to do other things after the "Activity" that are specific to the child process for my specific execution being complete.

Being possible to "lose" a task token isn't great either - the weird long-poll API they have for this, and no ability to get a task token again, is one reason I gave up on Activities previously.

Kind regards,
-baz
